server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.188.38:3307/flowable-env?allowPublicKeyRetrieval=true&&useSSL=false&&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&&zeroDateTimeBehavior=CONVERT_TO_NULL&&serverTimezone=GMT%2B8&&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
  modeler:
    context-root: /flowable-ui